name: TUF repository snapshot

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  tuf-snapshot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@e2f20e631ae6d7dd3b768f56a5d2af784dd54791
      - uses: actions/setup-python@13ae5bb136fac2878aff31522b9efb785519f984
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install git+https://github.com/vmware-labs/repository-editor-for-tuf.git

      - name: Sign targets
        working-directory: metadata
        env:
          TUF_REPO_PRIVATE_KEY_fb8a7fd2030a0d991af8855dc6093eb3029fee110f73abc63ee94e87ad50b2c2: ${{ secrets.TUF_REPO_PRIVATE_KEY_fb8a7fd2030a0d991af8855dc6093eb3029fee110f73abc63ee94e87ad50b2c2 }}
        run: |
          tufrepo --keyring=env sign --all-targets

      - name: Snapshot
        id: snapshot
        working-directory: metadata
        env:
          TUF_REPO_PRIVATE_KEY_38600820f11a5f7d7ff42e6dfc9b03fd60272a3be6f895da2d882cea8bb1e20f: ${{ secrets.TUF_REPO_PRIVATE_KEY_38600820f11a5f7d7ff42e6dfc9b03fd60272a3be6f895da2d882cea8bb1e20f }}
          TUF_REPO_PRIVATE_KEY_9d78543b508f99a95a3c31fad3cffef0644134f1a028b30501acc12058c7c3e8: ${{ secrets.TUF_REPO_PRIVATE_KEY_9d78543b508f99a95a3c31fad3cffef0644134f1a028b30501acc12058c7c3e8 }}
        run: |
          tufrepo --keyring=env snapshot
          # verify that result is a functional repository
          tufrepo verify --root-hash 24d9b03f10ce0fe2e648833de26af60a4a8cd4e65bb396a8200a3194ae8ea76e 
          # only set variable to true if we really did something
          git diff --quiet ||  echo "snapshot=true" >> $GITHUB_OUTPUT

      - name: Commit snapshot
        working-directory: metadata
        if: ${{ github.event_name == 'push' && steps.snapshot.outputs.snapshot == 'true'}}
        run: |
          tufrepo verify --root-hash 24d9b03f10ce0fe2e648833de26af60a4a8cd4e65bb396a8200a3194ae8ea76e

          git config user.name tufrepo
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git commit -a -m "Repository snapshot"
          git push
